apiVersion: v1
kind: Service
metadata:
  name: pose-estimation-service
spec:
  selector:
    app: pose-estimation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # The port on which your app is running inside the container
  type: LoadBalancer  # Type of service; for local testing, use NodePort
