name: Deploy Model

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Training Script
        run: |
          python tracking.py
          
      - name: Ensure the Best Model Directory Exists
        run: mkdir -p models/best_model

      - name: Copy the Best Model
        run: |
          if [ -f models/best_model.sav ]; then
            cp models/best_model.sav models/best_model/best_model.sav
          else
            echo "Best model not found!"
            exit 1
          fi

      - name: Build Docker image
        run: |
          docker build -t your-docker-image:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag your-docker-image:latest your-docker-username/your-docker-image:latest
          docker push your-docker-username/your-docker-image:latest

      - name: Clean up
        run: |
          docker system prune -f
