name: deploy.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine best model
        id: best-model
        run: |
          model_folder='./models/best_model/'
          if [ -d "$model_folder" ]; then
            latest_model=$(ls -t "$model_folder" | head -n 1)
            echo "BEST_MODEL=${latest_model}" >> $GITHUB_ENV
            echo "Best model determined: ${latest_model}"
          else
            echo "Model folder not found"
            exit 1

      - name: Build Docker image
        run: |
          docker build -t my-model-image .

      - name: Run Docker container
        run: |
          docker run --rm -e BEST_MODEL=${{ env.BEST_MODEL }} -v $(pwd)/models:/app/models my-model-image
