name: Build and Deploy Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracking script
        run: |
          python tracking.py

      - name: Find the best model
        id: find-best-model
        run: |
          BEST_MODEL=$(python find_best_model.py)
          echo "BEST_MODEL=${BEST_MODEL}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t my-model-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag my-model-image:latest ${{ secrets.DOCKER_USERNAME }}/my-model-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-model-image:latest
