name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-mlops-image:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-mlops-image:latest ${{ secrets.DOCKER_USERNAME }}/my-mlops-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-mlops-image:latest

      - name: Set up DagsHub and MLflow
        run: |
          pip install dvc dagshub mlflow
          dvc pull
          dagshub init
          mlflow set_tracking_uri "https://dagshub.com/MLOps-MaitriAI/pose-estimation.mlflow"

      - name: Run Tests
        run: |
          # Add your test commands here if any
          echo "Running tests..."
